// <auto-generated />
namespace App.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class intialDatabase1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intialDatabase1));
        
        string IMigrationMetadata.Id
        {
            get { return "202110171938486_intialDatabase1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
